"""add clubs table and team.club_id

Revision ID: 36936b7b91ff
Revises: a9472815ac80
Create Date: 2026-09-15 14:59:55.773602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36936b7b91ff'
down_revision: Union[str, None] = 'a9472815ac80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('teams', sa.Column('club_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_team_season_club', 'teams', ['season_id', 'club_id'])
    op.create_foreign_key(None, 'teams', 'clubs', ['club_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint('uq_team_season_club', 'teams', type_='unique')
    op.drop_column('teams', 'club_id')
    op.drop_table('clubs')
    # ### end Alembic commands ###
