"""add lineup_entries

Revision ID: 73b75e83e3a1
Revises: 57aef2887346
Create Date: 2026-09-24 15:39:44.512898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b75e83e3a1'
down_revision: Union[str, None] = '57aef2887346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineup_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('batting_slot', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=3), nullable=False),
    sa.Column('inning_entered', sa.Integer(), nullable=True),
    sa.CheckConstraint('batting_slot >= 1', name='ck_lineup_slot_positive'),
    sa.CheckConstraint('inning_entered IS NULL OR inning_entered >= 1', name='ck_lineup_inning_positive'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['roster_id'], ['rosters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineup_entries')
    # ### end Alembic commands ###
